
name: build

on:
  push:
    tags: ['v*']
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: "* * * * 0" # weekly on sunday

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build # SonarScan locks some files and breaks Build if done first
      run: |
        dotnet publish -r osx-x64 -p:PublishSingleFile=true --self-contained Eto.GifImageView.Demo
        dotnet publish -r linux-x64 -p:PublishSingleFile=true --self-contained Eto.GifImageView.Demo
        # wrap artifacts in tar archives to maintain permissions intact
        tar --directory=Eto.GifImageView.Demo/bin/Mac64/Debug/net6.0/osx-x64/publish -cvf Eto.GifImageView.Demo.Mac.tar Eto.GifImageView.Demo.app
        tar --directory=Eto.GifImageView.Demo/bin/Gtk/Debug/net6.0/linux-x64/publish -cvf Eto.GifImageView.Demo.Gtk.tar Eto.GifImageView.Demo

    - name: Upload Eto.GifImageView.Mac artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Eto.GifImageView.Demo.Mac
        path: Eto.GifImageView.Demo.Mac.tar

    - name: Upload Eto.GifImageView.Gtk artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Eto.GifImageView.Demo.Gtk
        path: Eto.GifImageView.Demo.Gtk.tar

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: |
        dotnet build -c Release Eto.GifImageView
        dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained Eto.GifImageView.Demo
    
    - name: Upload TestApp.Wpf artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Eto.GifImageView.Demo.Wpf
        path: Eto.GifImageView.Demo/bin/Wpf/Debug/net6.0-windows/win-x64/publish/Eto.GifImageView.Demo.exe

    - name: Upload nuget artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nuget
        path: Eto.GifImageView/bin/Release/*.nupkg

    - name: Push to nuget.org
      if: (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/'))
      run: dotnet nuget push '.\Eto.GifImageView\bin\Release\*.nupkg' --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}}
